---
- hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli
  ansible_network_os: cisco.ios.ios
  ansible_become: yes
  ansible_become_method: enable

  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: "{{ lookup('file', './vars/raw_banner.cfg') }}"
      state: present
  

  - name: SHOW RUN | BEG BANNER 
    ios_command:
      commands:
        - show run | beg Qousai
    register: banner

  - debug: var=banner.stdout_lines