---
- hosts: all
  gather_facts: false
  connection: network_cli


  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: "{{ lookup('file', './vars/raw_banner.cfg') }}"
      state: present
  

  - name: SHOW RUN | Sec BANNER 
    ios_command:
      commands:
        - show run | Sec Qousai
    register: banner

  - debug: var=banner.stdout_lines