---
- hosts: all
  gather_facts: no
  connection: network_cli

  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: "{{ lookup('file', './vars/raw_banner.cfg') }}"
      state: present
    when: ansible_network_os == false

  - name: SHOW RUN | BEG BANNER 
    ios_command:
      commands:
        - show run | beg Qousai
    register: banner

  - debug: var=banner.stdout_lines