---
- hosts: all

  tasks:
    - name: snmp ro/rw string configuration
      ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW