---
############ Working Playbook
- hosts: all

  tasks:
    - name: snmp ro/rw string configuration
      ios_config:
        commands:
          - no snmp-server community ansible-public RO
          - no snmp-server community ansible-private RW