---
############ Working Playbook
- hosts: all

  tasks:
    - name: snmp ro/rw string configuration
      ios_config:
        commands:
          - snmp-server community test2-public RO
          - snmp-server community Test-private RW