---
############ Working Playbook
- hosts: all
  gather_facts: false

  tasks:

  - name: Merge provided configuration with device configuration
    ios_l2_interfaces:
      config:
      - name: Ethernet0/0
        access:
          vlan: 10
      state: merged
